name: githubcontextdata
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: priting context data
        run: echo "${{ toJSON(github) }}"
      - name: cloning repo
        run: git clone "${{github.repositoryUrl}}"
