name: infra-deployment
on: 
  push:
    branches:
      - 'feature/**'
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
    checkout_code:
        runs-on: ubuntu-latest
        name: Checkout code
        outputs:
          artifact-id: ${{ steps.upload-artifact-files.outputs.artifact-id }}
        steps:
            - name: checkout-code
              uses: actions/checkout@v4
            - name : list-dev
              run: |
               ls ${{ github.workspace}}/dev/stacks/network
               cd ${{ github.workspace}}/dev/stacks/network
            - name: upload-artifact-files
              uses: actions/upload-artifact@v4
              with:
                name : my-first-artifact
                path: ${{ github.workspace }}
                if-no-files-found: error
    terraform-init:
      name: init-Terraform
      runs-on: ubuntu-latest
      needs: checkout_code
      steps:
        - name: Downlaoding-artifact
          uses: actions/download-artifact@v4
          with:
            name: my-first-artifact
            path: .
        - name: Setting aws credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::975050222078:role/oidc-role-for-github
            role-session-name: github-to-aws
            aws-region: us-east-1
        - name: setting up terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.1.7"  
        - name: init Terraform
          working-directory: ${{ github.workspace }}/dev/stacks/network
          run: |
           terraform init
           ls -la
        - name: plan terraform
          working-directory: ${{ github.workspace }}/dev/stacks/network
          run: |
           ls -la


