name: infra-deployment
on: workflow_dispatch
jobs:
    checkout_code:
        runs-on: ubuntu-latest
        name: Checkout code
        outputs:
          artifact-id: ${{ steps.upload-artifact-files.outputs.artifact-id }}
        steps:
            - name: checkout-code
              uses: actions/checkout@v4
            - name : list-dev
              run: |
               ls ${{ github.workspace}}/dev/stacks/network
               cd ${{ github.workspace}}/dev/stacks/network
            - name: upload-artifact-files
              uses: actions/upload-artifact@v4
              with:
                name : my-first-artifact
                path: ${{ github.workspace }}
                if-no-files-found: error
    terraform-init:
      name: Run-Terraform
      runs-on: ubuntu-latest
      needs: checkout_code
      steps:
        - name: Downlaoding-artifact
          uses: actions/download-artifact@v4
          with:
            name: my-first-artifact
            path: .
        - name: Setting aws credentials
          uses:     

