name: multiple-jobs
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
     - name: first-step
       run: echo " hi i am first step of the first job"
  secondjob:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
     - name: first-step
       run: echo "hi iam second task dependent on second task"
  thirdjob:
    needs: firstjob
    runs-on: ubuntu-latest
    steps:
     - name: third step
       run: echo "hi iam third job dependent on second task"     
