name: outputs-practice
on: workflow_dispatch
jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.first.outputs.test }}
        steps:
            - name: setting output
              id: first
              run: echo "test=Hello" >> $GITHUB_OUTPUT
    jobs2:
        name: job2
        runs-on: ubuntu-latest
        needs : job1
        steps:
            - name: fetching output
              run: echo "output is ${{needs.jobs1.outputs.output1}}"
